"""added about user

Revision ID: 11126ad0275e
Revises: add71a7a1dd5
Create Date: 2020-05-24 22:18:39.521766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11126ad0275e'
down_revision = 'add71a7a1dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_user')
    # ### end Alembic commands ###
